### ISSUE TITLE
stabilize plugin and improve memory footprint and performance

### ISSUE THREAD

**Issue by abloch** [botimonline/botz#11]

**Comment by mderazon** [comment]
Hi. 
Got here from @noam-r tweet.

Would like to help in any way I can, What about a Chrome extension ? Is it planned ? I can take a shot at that.

Also, I see it's currently working against a mock api, is there a real api in the works ? Is it open source ? Can help there as well

**Comment by eranshmil** [comment]
@mderazon Hi, please DM me your phone number.
https://twitter.com/eranshmil
